services:
  app:
    build:
      context: ./docker/app
    ports:
      - '${FORWARD_HTTP_PORT:-80}:80'
    volumes:
      - app:/var/www/html
      - ./docker/app/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/app/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/app/conf/000-default:/etc/apache2/sites-available/000-default
      - ./docker/app/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/app/conf/schemaspy.properties:/var/www/schema/schemaspy.properties
    working_dir: /var/www/html
  cron:
    build:
      context: ./docker/cron
    volumes:
      - app:/var/www/html
      - ./docker/cron/cron.d/app:/etc/cron.d/app
    depends_on:
      - app
  mail:
    build:
      context: ./docker/mailpit
    ports:
      - '${FORWARD_MAILPIT_PORT:-8025}:8025'
  database:
    build:
      context: ./docker/database
    ports:
      - ${FORWARD_DB_PORT:-5432}:5432
    environment:
      POSTGRES_COLLATE: ${DB_COLLATE:-en_US.utf8}
      POSTGRES_INITDB_ARGS: "--lc-collate=${DB_COLLATE:-en_US.utf8} --lc-ctype=${DB_COLLATE:-en_US.utf8}"
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/database/init:/docker-entrypoint-initdb.d
  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.jp}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-password}'
    ports:
      - '${FORWARD_PGADMIN4_PORT:-8888}:80'
    volumes:
      - pgadmin4:/var/lib/pgadmin
    depends_on:
      - database
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    ports:
      - ${FORWARD_NGROK_PORT:-4040}:4040
    volumes:
      - ./ngrok.yaml:/etc/ngrok.yml
volumes:
  app:
  database:
  pgadmin4: